pipeline
{

agent {
  label 'Prod'
}

stages{

    stage('build')
    {
        steps {
            echo 'Hi this is sainath first build'
        }
        post {
      success {
    // One or more steps need to be included within each condition's block.
  }
}
}
}
}