pipeline
{

agent none
stages{

    stage('build')
    {
        steps {
            echo 'Hi this is sainath first build'
        }
    }

    stage('test')
    {
        steps {
            echo 'Hi this is sainath first test'
        }
    }

    stage('deploy')
    {
        steps {
            echo 'Hi this is sainath first deploy'
        }
    }   

}
}